### ISSUE TITLE
Question related to Benchmark test read time

### ISSUE THREAD

**Issue by AveryQi115** [XinyuZeng/EvaluationOfColumnarFormats#2]
Hi, I have a conceptual question related to the benchmark read time stats.

In the paper, it is described as `Given this, we focus on the raw scan performance of each storage format. We preallocate a fixed-sized memory buffer. After decoding the fixed-size unit of data, the system writes the result to the same buffer, assuming that the previous one has already been consumed by upstream operators.`

With further look at the code, I find that it uses batch_size and the batch_size looks like the count for the number of tuples instead of the buffer size as following code shows, https://github.com/XinyuZeng/arrow-Public/blob/c0710dde42720f562bd419e43ca39a2549aff70e/cpp/src/parquet/file_reader.cc#L941

Can I assume batch_size is the number of tuples read in the benchmark read experiment for both parquet and orc?

I'm trying to run the experiments on btrblock and I wanna make sure the experiment settings are aligned. Thanks for any explanation.

**Comment by XinyuZeng** [comment]
Yes. The batch size should be 1024 for both parquet and orc. The reason is that we wanted to eliminate memory allocation time and only measure decoding/decompression. Because Arrow and Orc's memory allocation has different performance.

Maybe decoding a btrfile(several blocks) to the same 64k in-memory block or just does not record the time for init the blocks?
